### ISSUE TITLE
Compatibility with other PS ports

### ISSUE THREAD

**Issue by pedropsi** [pedropsi/puzzlescript-game-bar#11]
Especially Dario's

**Comment by minotalen** [comment]
Prelude functions sprite_size and case_sensitive function as expected. Opacity also works.
Only issue I can find is that the noSave function does not trigger. Workaround I presented has fuctioning nosave, but win does not get triggered during all nosave moves (try on my gh.io, after all targets are covered, player needs to walk against the level boundary to complete it.

In my fork: irreversible does not trigger, even with disabled nosave. All irreversible does is  `backups = []`, so I'm suspecting the game bar stores backups separately or cancels the deletion somehow.

**Comment by pedropsi** [comment]
I'm currently trying to reduce the number of functions that the game bar overwrites to a minimum. Then I suspect this issue will disappear.

**Comment by pedropsi** [comment]
I've verified in your fork that both keywords "noSave" and "irreversible" act through the processInput function.
Since meanwhile this function is no longer overwritten by the game bar, the issue must be gone!

**Comment by pedropsi** [comment]
I'll wait for your confirmation and then close the V1 milestone :)
