### ISSUE TITLE
Fullscreen button sometimes stays highlighted

### ISSUE THREAD

**Issue by minotalen** [pedropsi/puzzlescript-game-bar#14]
**What is the Problem / bug**
When entering fullscreen while on title screen, then hitting ESC direclty after the FS button stays highlighted even though game is not in fullscreen mode.

**How can it be reproduced?**
No inputs (key or mouse) may be made between entering and leaving fullscreen mode. Need to be on the title screen.

**System information:**
 - OS: Win10
 - Browser Chrome
 - Version 76.0.3809.87

**Comment by minotalen** [comment]
COuld you reproduce the bug?

**Comment by pedropsi** [comment]
I will try to capture the ESC key for a while until it's safe to deactivate fullscreen. Let's see if this works.

**Comment by pedropsi** [comment]
Turns out capturing ESC is not allowed in fullscreen - but meanwhile this seems solved?
