### ISSUE TITLE
Linear Progression, X at a time.

### ISSUE THREAD

**Issue by minotalen** [pedropsi/puzzlescript-game-bar#16]
**Why**
The current linear progression that PS enforces means players can easily get stuck if there is a single level they are not able to solve. 
Making all levels accessible from the beginning might be a workaround, but that takes away the joy of progression/unlocking. (I'd argue a game is generally more fun if you are not aware of how much of it you have left.)

Having a set amount of X unlocked levels at a time means the player can skip X-1 levels before having to return to solve them. This would result in a semi-linear progression that is not one-size-fits-all and should improve overall completion rates.

**What**
Create a progression logic that allows for X levels to be unlocked at a time. Create logic for hiding/greying out locked levels.
Ideally there should be additional logic that allows for keeping the final level locked until all previous levels have been beaten (to encourage players towards 100%ing the game).

**How**
make a variable 'progression type', set to 'all' by default. can be set to linearX.
make a variable 'locked appear'. if true, all locked levels appear greyed out at the start. if false, new levels are hidden and only appear after they've been unlocked.

**Comment by pedropsi** [comment]
Implementation notes:

var LevelLookahead=2;	//Max number of unsolved levels shown, in linear progression
/* 0 means all are shown, the default option */
var bossLevels=[10,20,35]; 		//Boss levels require beating all previous levels to show up in selector; plus all next levels will be hidden until the boss level is beaten
/* [] means there are no boss levels, the default option */
