### ISSUE TITLE
Mobile version shows regular mobile hamburger menu instead of game-bar

### ISSUE THREAD

**Issue by minotalen** [pedropsi/puzzlescript-game-bar#23]
**What is the Problem / bug**
When opening an export with added game-bar on a mobile device the old style mobile menu seems to overwrite the game-bar. Might relate to #11 (but I think issue exists on the main PS branch as well)

**How can it be reproduced?**
open minotalen.itch.io on a mobile device.

**How might it be fixed?**
either by making a custom PS fork that removes the mobile menu or by adding a step to the setup where the user manually removes the old mobile menu.

**Comment by minotalen** [comment]
this might possibly belong to v1 (supposing it 'breaks' most exports on mobile) so I've added it there

**Comment by pedropsi** [comment]
Thanks! Indeed it would belong to V1. It's fixed now, I think.

**Comment by pedropsi** [comment]
I'll wait for your confirmation and then close the V1 milestone :)
