### ISSUE TITLE
SEO Optimisation

### ISSUE THREAD

**Issue by pedropsi** [pedropsi/puzzlescript-game-bar#34]
**What is the Problem / bug**
Results don't show up at top of google search

**How can it be reproduced?**
Search "pedropsi game bar"

**Comment by pedropsi** [comment]
![](https://cdn.discordapp.com/attachments/551849001734111254/609754939291467788/unknown.png)

**Comment by minotalen** [comment]
I think it might have moved to #3 but then again maybe I'm getting personalized results?

**Comment by pedropsi** [comment]
It got moved to 3rd. Probably ok since the first two results are related?

**Comment by minotalen** [comment]
Guess it might move up over time if people click on it. Closing 😊
