### ISSUE TITLE
Function missing to implement music

### ISSUE THREAD

**Issue by minotalen** [pedropsi/puzzlescript-game-bar#36]
**Why**
Function ToggleCurrentSong seems to be missing.

**What**
index.html:7 Uncaught ReferenceError: ToggleCurrentSong is not defined
    at HTMLDivElement.onclick

**Comment by pedropsi** [comment]
Solved?

**Comment by minotalen** [comment]
now it gives
index.html:1 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
checkAudioContextExists @ index.html:1

**Comment by pedropsi** [comment]
Browsers require one user interaction before music is allowed to start. Apart from that is it working now?
 (I've added more missing functions)

**Comment by pedropsi** [comment]
To reopen if needed
