### ISSUE TITLE
refocusing gameC with open level select loads start menu

### ISSUE THREAD

**Issue by minotalen** [pedropsi/puzzlescript-game-bar#39]
**How can it be reproduced?**
Finish a level, then open level select. Refocus the game and press an arrow key.

Selecting 'start game' overwrites the savefile. Being able to load this screen should provide useful for the 🖫 button, since that provides another 'confirmer'. Instead of erasing the cookies just load the start screen when the 🖫 button is clicked. The user can then cancel by opening any level from level select instead of confirming.

**Screenshots/Additional info**
![image](https://user-images.githubusercontent.com/29110130/62999973-4ed97700-be70-11e9-8d2c-442b31d5007f.png)

**Comment by pedropsi** [comment]
Solved (unless user is an extremely fast clicker). Refocusing on game closes the window.
