### ISSUE TITLE
shows start screen on reload instead of continue

### ISSUE THREAD

**Issue by minotalen** [pedropsi/puzzlescript-game-bar#43]
![image](https://user-images.githubusercontent.com/29110130/63059032-91da2f80-beee-11e9-81f3-b85442f1ba65.png)
to make things worse, selecting 'start game' clears the savefile :(

**Comment by minotalen** [comment]
only when level 1 has not been solved

**Comment by minotalen** [comment]
![image](https://user-images.githubusercontent.com/29110130/63059678-56d8fb80-bef0-11e9-8c70-b0bc107e84ca.png)
also somehow works here

**Comment by minotalen** [comment]
ah it's because darios port has its own doSetupTitleScreenLevelContinue()

**Comment by pedropsi** [comment]
I can't reproduce so I think this was somehow fixed meanwhile!
